const COMMON_CODES = {
    NETWORK_ERROR: 'Network Error',
    TIMEOUT_ABORTED: 'ECONNABORTED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_TOKEN_CODE: 413
};

const EDAM_CODES = {
    PERMISSION_DENIED: 3,
    INVALID_AUTH: 8,
    AUTH_EXPIRED: 9
};

const GRPC_CODES = {
    CONTENT_lOADED_FAILED: 11003,
    PERMISSION_DENIED: 11004,
    INTERNAL_ERROR: 11009,
    ACCOUNT_DEACTIVATION: 11010,
    AUTH_EXPIRED: 11005,
    SENSITIVE_CONTENT: 11008,
    TRAFFIC_EXCEEDED: 22005,
    SERVER_ERROR: 22006,
    TOO_FREQUENT: 11006,
    REACHED_LIMIT: 11007,
    FORMAT_ERROR: 22222
};

export {
    // eslint-disable-next-line import/prefer-default-export
    COMMON_CODES,
    EDAM_CODES,
    GRPC_CODES
};
export default {
    ...COMMON_CODES,
    ...EDAM_CODES,
    ...GRPC_CODES
};
